### ISSUE TITLE
[1.10.2] Turbine rotors invisible

### ISSUE THREAD

**Issue by llloyd4** [ZeroNoRyouki/BigReactors#67] opened 2017-01-07 00:31 UTC
Well, this puts the turbine project on hold. So, I built a 7x7x14, 10 quad blades, so 8 blades per shaft piece (4 double blades so 8 pieces per blade) for 80 blades. At first, while breaking the coil apart to swap for another metal (experimenting to try and find the best coil metal) I accidentally broke the rotor shaft but it was still there in ghost form so it didn't seem like I broke it. After a few more experiments and just placing the shaft in using the outline box to determine which one was broken, I decided to close back to the main menu and reload the world to try and fix and that caused all the rotor blades and shaft pieces to completely vanish. They are still there, you can see the outline of the box, but they are completely invisible. I even restarted the entire game, closed completely out, closed the client, restarted the client, restarted Minecraft, nada, still invisible.  This is Extreme Reactors 2.0.4.5.23.

**Comment by RogueLogic** [comment] 2017-01-07 00:52
To fix your issue, turn the turbine off before breaking it.

The actual issue is known and caused by the turbines being rendered by the rotor barring when the turbine is active, causing them to effectively disappear when the barring is too far out of your fov. If you look at the barring they should re-appear.

**Comment by llloyd4** [comment] 2017-01-07 02:38
Barring?

**Comment by RogueLogic** [comment] 2017-01-07 20:28
I was referring to the Rotor bearing (thank spell check and mobile keyboards). That also only applies when the turbine is built and active. attempt to rebuild your turbine and disable it before breaking a block.

**Comment by llloyd4** [comment] 2017-01-08 01:31
It won't reform, I broke some parts off and was trying to figure out which when I restarted the client and it all vanished instead of broken bits remaining ghosted.

**Comment by RogueLogic** [comment] 2017-01-08 04:30
the turbine should give you an error read out, follow that and you should be good.

**Comment by ZeroNoRyouki** [comment] 2017-01-10 21:37
Fixed in the next release

**Closed by ZeroNoRyouki** 2017-01-10 21:37 UTC
