### ISSUE TITLE
Reactors in Active cooling will not work after a server restart.

### ISSUE THREAD

**Issue by patrix87** [ZeroNoRyouki/BigReactors#98] opened 2017-04-13 12:12 UTC
I've noticed that many times, note that I'm on FTB Beyond 1.3.0
That is also true in single player games.

After a restart the reactor produces 0 steam and does not receive water.

The only fix is to break one block from the reactor and the turbine then replace the block on the reactor first, then on the turbine. Then break the one from the reactor again 5 to 6 times while looking at the controller screen between each time to look for 2000mb/t.

I'm not sure what is wrong but something is not liking restarts.

**Comment by RogueLogic** [comment] 2017-04-13 13:47
#59

**Comment by StefanTT** [comment] 2017-04-26 17:46
On my map it is still broken in version 0.4.5.28.
This is the latest version.

**Comment by ZeroNoRyouki** [comment] 2017-04-27 07:36
Yup, I know. That release did not address this issue

**Comment by StefanTT** [comment] 2017-04-27 07:39
Ok that explains it. I was somewhat irritated because in #59 it reads like it should be already fixed by now.

**Comment by Tops420** [comment] 2017-05-02 17:39
Also experiencing this tedious bug, any update for a fix or a work around?

**Comment by StefanTT** [comment] 2017-05-02 20:30
My workaround is to have the game transfered to my server and have it running all the time in a docker container which I can pause.

The other workaround is to break/recreate the reactor every x minutes. This does less harm than breaking the turbine. But this only works if the fluid ports faced in a specific direction during creation of turbine/reactor. Unfortunately I cannot tell you the direction as I played around with the direction and now breaking the reactor helps nothing.

It's a pity, this bug is almost a show stopper for me, to be honest.

**Comment by Tops420** [comment] 2017-05-02 21:20
Unfortunately running a multiplayer server with FTB Beyond while having scheduled server restarts renders the use of a turbine impractical. Like you, i remove both controllers and place them randomly until it starts working correctly. 

Hope this issue gets resolved in the next update, Do love this mod and thank you Zero for porting it to 1.10 :)

**Comment by ZeroNoRyouki** [comment] 2017-05-08 07:17
OK so, I think I removed the root issue that's preventing the two multiblocks to connect properly with each other sometimes. I'm currently testing the new code and, if all goes well, I will push out a new release soon

**Comment by StefanTT** [comment] 2017-05-08 08:20
Ah, great. I can / will test it then as soon as possible.

**Comment by ZeroNoRyouki** [comment] 2017-05-10 16:28
I've just pushed out 0.4.5.29 with should solve the connection issue once and for all

**Comment by StefanTT** [comment] 2017-05-10 17:29
I tried to proof that you are wrong, but failed.
In other words: confirmed, it fixes the issue for me.
Great work, thank you very much!

**Comment by ZeroNoRyouki** [comment] 2017-05-11 07:34
Good :)
Thank you, too
Z

**Closed by ZeroNoRyouki** 2017-05-11 07:34 UTC
