### ISSUE TITLE
[1.12.1] Ignored smelting recipe

### ISSUE THREAD

**Issue by UnPure** [ZeroNoRyouki/BigReactors#135] opened 2017-09-28 11:33 UTC
While starting a server/client, ER is producing a log entry about an ignored smelting recipe.

    [Server thread/INFO] [FML]: Ignored smelting recipe with conflicting input: 1xitem.coal@1 = 1xitem.bigreactors:ingotmetals@2

I see no issues about any recipes in game, but i still think something is wrong with the recipes.

**Extreme Reactors:** 0.4.5.40
**Forge:** 14.22.0.2475

**Comment by ZeroNoRyouki** [comment] 2017-09-28 11:41
That will happen when 2 mods add a smelting recipe for the same input item.

There is probably another mod that's is running before ER in your pack that add a smelting recipe for coal and so mine (graphite ingot) is ignored

**Comment by UnPure** [comment] 2017-09-28 11:56
I removed Extreme Reactors for testing but besides fuel and crafting recipes, there is nothing else that smelts coal in JEI.
Also if i throw some coal in my furnace, nothing is happening.

**Comment by ZeroNoRyouki** [comment] 2017-09-29 18:58
You are right, the conflict is caused by my own charcoal to graphite recipe. The fix will be included in the next release

**Closed by ZeroNoRyouki** 2017-09-29 18:58 UTC
