### ISSUE TITLE
Turbine STOPPED accepting steam for a reactor

### ISSUE THREAD

**Issue by Kehny91** [ZeroNoRyouki/BigReactors#59] opened 2016-12-20 16:00 UTC
Hello. 
First, nice job, I really loved Big Reactor :)

Here is my setup:
![2016-12-20_16 32 14](https://cloud.githubusercontent.com/assets/24680857/21356453/eeef2904-c6d1-11e6-96a6-18203504ee6c.png)

There is a 7x7 reactor in a center and a Turbine on each face of the reactor.
When i built this, 3 of the four turbines were working fine. The fourth one never spinned (never accepted steam)
And the day after, a second one stopped working... (Without any modification to the setup)
I have the last version of Zero core and Extreme reactor
Water is pump via a mekanism pump.
Every Turbine has a Power tap and a Dimensional Transceiver (ender io) attached to.
The metal block I am usiing is Manyulyn block (Tinker's)

The GUI of a working Turbine:
![2016-12-20_16 50 39](https://cloud.githubusercontent.com/assets/24680857/21357178/8f407a82-c6d4-11e6-978c-f006b9c34c9d.png)

The GUI of a not working Turbine:
![2016-12-20_16 50 49](https://cloud.githubusercontent.com/assets/24680857/21357187/9bfe68d8-c6d4-11e6-809a-71882e031450.png)

The GUI of the Reactor:
![2016-12-20_16 51 02](https://cloud.githubusercontent.com/assets/24680857/21357205/a83c60d2-c6d4-11e6-87d2-145adc129e65.png)

There is no pipe beetween the reactor and the turbines (it's just coolant ports face to face)
On each face of the reactor, there is 2 coolant port.

Also, i have graphics problem. I can see the blades only if I look at them with a precise "head rotation/inclinasion"...

Help me, I was so proud of my setup ><
Sorry for my approximate English ^^
Goodluck

**Comment by ZeroNoRyouki** [comment] 2016-12-21 22:46
The block-to-block connection still work. There may be an issue with the order in which the multiblocks are assembled. Break one block of the not working turbine and then replace it and let me know if this fix it

The graphics problem is fixed, a new release should come out in the next few days (holidays notwithstanding)

**Comment by Kehny91** [comment] 2017-01-01 19:02
Actually, each time I reload my world, two turbines stop.
To be reactivated, I have to break and replace a block from the reactor

**Comment by Kehny91** [comment] 2017-01-02 15:13
Yes, breaking the turbine doesn't help.
The failing turbines are the one which are at the north and at the west of the reactor.
I don't think it is chunk related, the reactor is quite at the center of a chunk. Each and every turbine is splitted in half by a chunk border.

**Comment by RogueLogic** [comment] 2017-01-03 03:09
This is a problem with the turbine as with ER 0.4.5.22 and ZC 0.0.8.2 with my own reactor the turbine would not accept steam directly attached until i broke and replaced my port. does your port deal with facing correctly when not built?

**Comment by Kehny91** [comment] 2017-01-04 17:31
I said in my last post:
"The failing turbines are the one which are at the north and at the west of the reactor."

North and West aren't opposite :P

Thank you for helping :)

**Comment by RogueLogic** [comment] 2017-01-04 17:39
*when your busy you tend to skim things*

@ZeroNoRyouki i there is enough information here for you to fix it. Most likely that the blocks to not properly register the Fluid capability int he correct direction until the turbine is built. this would be the case for mine as i check at every block update and or a capability from the opposite direction.

**Comment by ZeroNoRyouki** [comment] 2017-01-04 20:02
That's not the problem

**Comment by Kehny91** [comment] 2017-01-04 22:23
@ZeroNoRyouki 
Would you like me to find a way to give you my world ?

**Comment by ZeroNoRyouki** [comment] 2017-01-04 22:54
I've already found what's going on and reproduced the issues locally. Working on a fix
Thank you for the offer anyway :)

**Comment by ZeroNoRyouki** [comment] 2017-01-09 19:55
Fixed in the next release

Thank you for the report

**Closed by ZeroNoRyouki** 2017-01-09 19:55 UTC
Labels: bug, more information needed

**Comment by StefanTT** [comment] 2017-04-20 14:54
Sorry to warm up this issue, but I am a bit confused.
Should the problem of the not connected fluid ports be fixed in version 1.10.2-0.4.5.28 ?
Because for me it still seems broken.

I am using FTB Infinity Lite 1.10 with manually updated ExtremeReactors.

**Comment by miiichael** [comment] 2017-10-22 16:19
I'm also seeing the same problem with my setup (Minecraft 1.11.2, Forge 13.20.1.2454, ZC 0.1.0.6, ER 0.4.5.30. Though I'm recovering by breaking and replacing Thermal Dynamics fluiducts I'm using, as briefly breaking the reactor or turbine doesn't seem to help.
