### ISSUE TITLE
Reactor turns off when chunks unload

### ISSUE THREAD

**Issue by UntouchedWagons** [ZeroNoRyouki/BigReactors#46] opened 2016-11-11 02:19 UTC
Hi there, I am using the Infinite Lite pack which uses version 0.4.5.18. Whenever I leave my base or the server resets, my reactor shuts off and I have to turn it back on. I asked another person on the server if they were having this issue but they said they didn't. The power monitor controls the fuel rod levels so when the capacitor bank gets low the fuel rods react and when it gets 85% full the fuel rods get set to 100%. I tried using a max delay repeater there to try and automatically turn the reactor on when it loads but that doesn't work either.

![2016-11-10_21 16 41](https://cloud.githubusercontent.com/assets/160996/20202148/1081dcee-a78b-11e6-9cad-a3ee5c6f2a80.png)

**Comment by RogueLogic** [comment] 2016-11-11 06:11
What version of ZeroCore are you using? 0.0.8.0 had a problem that could have cause this that was fixed in 0.0.8.1.

**Comment by RogueLogic** [comment] 2016-11-11 06:23
NVM, I looked into the modpack. Please update to 0.0.8.1 as there was an issue (ZeroNoRyouki/BigReactors#41) with non correct multiblocks building that may also be the cause of this issue.

**Comment by UntouchedWagons** [comment] 2016-11-11 15:42
Unfortunately I'm playing on a server, so updating the mod won't be possible. Thanks for looking into it though.

**Comment by RogueLogic** [comment] 2016-11-11 16:15
If updating it not possible a remedy would be to have a computer that constantly turns the reactor on, Or a Redstonee clock doing so.

**Comment by UntouchedWagons** [comment] 2016-11-14 23:04
The server I play on was updated to Infinity Lite 1.1.0 which has ZeroCore 0.0.8.1 but my reactor still shuts down when the chunks unload

**Comment by RogueLogic** [comment] 2016-11-15 04:51
Could you provide the chunk information and details on how you have the reactor connected to your battery?

**Comment by UntouchedWagons** [comment] 2016-11-15 15:40
Certainly
![2016-11-15_10 37 47](https://cloud.githubusercontent.com/assets/160996/20311940/9e4ed44a-ab1f-11e6-8f1a-48d2a8785929.png)
![2016-11-15_10 37 58](https://cloud.githubusercontent.com/assets/160996/20311941/9e5c15a6-ab1f-11e6-9588-4170931e1d78.png)


The reactor straddles 2 chunks and is connected to my capacitors via the tier 2 enderio energy conduits.

**Comment by UntouchedWagons** [comment] 2016-11-15 17:37
When I say "Off" I mean off, not 100% insertion. I have to go into the controller UI and manually turn the reactor on everytime I go to my base

**Comment by ZeroNoRyouki** [comment] 2016-11-15 21:08
What are the settings of the power monitor and of the redstone port ?

**Comment by UntouchedWagons** [comment] 2016-11-15 22:00
The power monitor is set to provide a redstone signal when the energy stored in the battery is <10% then disable the redstone signal when >85%. The redstone port is set to 0% insertion with a redstone signal and 100% insertion without a signal.

**Comment by ZeroNoRyouki** [comment] 2016-11-15 22:45
OK so you don't turn it back on with the power monitor. 

If the multiblock is broken (by you or by a chunk being unloaded) the Reactor shut itself off automatically. What's probably going on, depending on the order in witch the chunk of your world are getting unloaded and saved to disk, is that a chunk containing part of the Reactor is being unload, the multiblock get broken up and the Reactor shutdown, then the remaining chunks are unloaded too and the Reactor state is saved to disk (as "not active"). When you log back in the multiblock is reformed and the Reactor read back it's state from disk (again, "not active"). 

There is not much do be done here I'am afraid, this is the correct behavior. You have to move your reactor inside a single chunk or keep those chunk loaded

**Comment by RogueLogic** [comment] 2016-11-15 23:24
if I'm correct shouldn't a reactor broken by unloaded chunks stay running (paused) and save to disk as such?

**Comment by UntouchedWagons** [comment] 2016-11-17 22:27
Okay so I moved the reactor so that it's not straddling multiple chunks and it stays on when chunks unload, a bit of an annoying work-around but it'll work till I have a more permanent spot for the reactor.

**Closed** 2016-11-18 00:24 UTC

**Comment by UntouchedWagons** [comment] 2016-11-18 00:25
This is still going to be an issue going forward because in 1.7 you could build reactors that straddled chunks and it wasn't a problem.

**Comment by RogueLogic** [comment] 2016-11-18 01:14
Zero this problem is not something you can just shrug off. When a chunk is unloaded onMachinePaused() shouldcalled, *obv.* because it is doing nothing in MultiblockReactor this should not affect this issue. The only way for this issue to be cause it for onMachineDisassebled() to be called, *again, obv.* When a chunk unloads onMachineDisassembled() should not be called, *obv.* This issue seem to stem from ZeroCore yet again.
