### ISSUE TITLE
Extreme Reactors 1.11.2-0.4.5.40 makes Graphite Blocks uncraftable

### ISSUE THREAD

**Issue by sandalle** [ZeroNoRyouki/BigReactors#133] opened 2017-09-21 05:49 UTC
Extreme Reactors ~1.12-0.4.5.40~ 1.11.2-0.4.5.40 makes Graphite Blocks uncraftable and both Graphite Bars and Graphite Blocks lost their [Project E](https://minecraft.curseforge.com/projects/projecte) EMC values they had before.

The items still exist and if I take nine Extreme Reactors Graphite Bars (ingots) into a 3x3 crafting grid, no Graphite Block is allowed in the output and [Just Enough Items](https://minecraft.curseforge.com/projects/just-enough-items-jei) doesn't show an Extreme Reactor Graphite Block as a valid crafting from Extreme Reactor Graphite Bars, though other items are craftable by Extreme Reactor Graphite Bars.

I also have [NuclearCraft](https://minecraft.curseforge.com/projects/nuclearcraft-mod) 2.4a installed which has its own Graphite Bars and Blocks, but both of those are still craftable and kept their EMC values.

**Comment by ZeroNoRyouki** [comment] 2017-09-21 09:10
Hi, I've checked it but the recipe for Graphite Blocks is working fine:

![133_2](https://user-images.githubusercontent.com/7107662/30686986-33b862ce-9eba-11e7-8701-72400374527e.png)

![133_3](https://user-images.githubusercontent.com/7107662/30686992-3b55d1ce-9eba-11e7-9ee8-177daddb4a1b.png)

Maybe another mod in your pack is messing around with my recipies

I've also tried to add  NuclearCraft but I can't find an 1.12 version

**Comment by sandalle** [comment] 2017-09-21 15:30
Ahh, sorry, I forgot to include the versions tested and I copied the Extreme Reactors version from the page I was on, not from what I'm using int he mod:
Minecraft: 1.11.2
Forge Mod Loader: 1.11.2-13.20.1.2476
ExtremeReactors: 1.11.2-0.4.5.40
Zero Core: 1.11.2-0.1.1.0
NuclearCraft: 2.4a-1.11.2

I also have [UniDict](https://minecraft.curseforge.com/projects/unidict) installed. The modpack (updates haven't been released yet) is https://minecraft.curseforge.com/projects/nst-unofficial-exploration if that helps testing.

**Comment by sandalle** [comment] 2017-09-22 02:22
Weird, I tried the update to ExtremeReactors: 1.11.2-0.4.5.40 and Zero Core: 1.11.2-0.1.1.0 again on Minecraft 1.11.2 with an existing SSP world instead, and did _not_ have this issue (both EMC values persisted and Graphite Blocks were craftable). I'll do some more testing, including copying my SMP world which did have the issue to try in SSP and few SMP tests (I have backups ;)).

**Comment by sandalle** [comment] 2017-09-22 02:46
Ahh, but in my current SSP test, the Ludicrite Block becomes uncraftable and Ludicrite Ingot lost its EMC. Downgrading to Extreme Reactors 1.11.2-0.4.5.30 and Zero Core 1.11.2-0.1.0.6 restores the EMC for Ludicrite and makes Ludicrite Block craftable again. This is with an existing SSP world and also a new SSP world. I did _not_ try regenerating the Extreme Reactors configs yet to see if that helps.

I also tried creating a new SSP world and had Ludicrite Blocks uncraftable.

**Comment by ZeroNoRyouki** [comment] 2017-09-22 06:02
Hi, last night I found a problem with the new system I now use to register objects in the game that could be the cause of what you are experiencing 

I pushed out a new release for 1.10 and 1.11.2 and it was approved on Curse late in the night. Could you test it again with that new version (.41)?

**Comment by sandalle** [comment] 2017-09-22 06:49
I'll take a look in the morning, thank you for hopefully fixing it. :)

**Comment by sandalle** [comment] 2017-09-22 16:53
With ExtremeReactors 1.11.2-0.4.5.41.jar and ZeroCore 1.11.2-0.1.1.0.jar, the Graphite Bar (ingot) and Block kept their EMC and were both craftable, but now Ludicrite Ingot lost its EMC and the Block has a weird crafting recipe:

Ludicrite Block recipe:
![ludicrite block recipe](https://user-images.githubusercontent.com/2447608/30754857-420cf5aa-9f79-11e7-81d3-431984693dd1.png)

Ludicrite Ingot uses:
![ludicrite ingot uses](https://user-images.githubusercontent.com/2447608/30754890-5fafe87e-9f79-11e7-825a-2aa952c643ea.png)

Same issue in a new SSP world _and_ in a new SSP world after wiping all of my current configs (so brand new configs).

I do see these in my server logs with an existing world, if that helps.
```
[09:29:50] [Server thread/DEBUG] [FML/]: Unable to lookup bigreactors:ingotmetals for public static erogenousbeef.bigreactors.common.item.ItemBRMetal erogenousbeef.bigreactors.init.BrItems.ingotMetals. This means the object wasn't registered. It's likely just mod options.
[09:30:37] [Server thread/INFO] [FML/bigreactors]: Ignored smelting recipe with conflicting input: 1xitem.coal@1 = 1xitem.bigreactors:ingotmetals@2
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorcasing: 237 (init) -> 1616 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorcomputerport: 246 (init) -> 1625 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbinepowertaptesla: 254 (init) -> 1633 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorcoolantport: 243 (init) -> 1622 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:brore: 235 (init) -> 1614 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorpowertaptesla: 241 (init) -> 1620 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbinecreativesteamgenerator: 261 (init) -> 1639 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorcreativecoolantport: 249 (init) -> 1628 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorcontrolrod: 244 (init) -> 1623 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbinerotorblade: 260 (init) -> 1638 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorredstoneport: 247 (init) -> 1626 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorrednetport: 245 (init) -> 1624 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbineglass: 250 (init) -> 1629 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorglass: 238 (init) -> 1617 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorcontroller: 239 (init) -> 1618 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbinefluidport: 257 (init) -> 1635 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:cyanite: 263 (init) -> 1641 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbinepowertaprf: 253 (init) -> 1632 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorpowertaprf: 240 (init) -> 1619 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:yellorium: 262 (init) -> 1640 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbinehousing: 251 (init) -> 1630 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbinecomputerport: 256 (init) -> 1634 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbinerotorshaft: 259 (init) -> 1637 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbinecontroller: 252 (init) -> 1631 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:turbinebearing: 258 (init) -> 1636 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:blockmetals: 236 (init) -> 1615 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactorfuelrod: 248 (init) -> 1627 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:blocks id mismatch bigreactors:reactoraccessport: 242 (init) -> 1621 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorcasing: 4119 (init) -> 6147 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinehousingcores: 4101 (init) -> 6175 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinepowertaptesla: 4124 (init) -> 6164 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:brore: 4105 (init) -> 6145 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorcreativecoolantport: 4113 (init) -> 6159 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorcontrolrod: 4127 (init) -> 6154 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinerotorblade: 4104 (init) -> 6169 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorrednetport: 4108 (init) -> 6155 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbineglass: 4118 (init) -> 6160 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:wrench: 4102 (init) -> 6176 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinefluidport: 4114 (init) -> 6166 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:ingotmetals: 4097 (init) -> 6171 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorpowertaprf: 4120 (init) -> 6150 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinehousing: 4109 (init) -> 6161 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinecontroller: 4116 (init) -> 6162 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinebearing: 4107 (init) -> 6167 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:blockmetals: 4106 (init) -> 6146 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:minerals: 4099 (init) -> 6173 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorfuelrod: 4128 (init) -> 6158 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorcomputerport: 4125 (init) -> 6156 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorcoolantport: 4115 (init) -> 6153 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorcasingcores: 4100 (init) -> 6174 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorpowertaptesla: 4117 (init) -> 6151 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinecreativesteamgenerator: 4103 (init) -> 6170 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorredstoneport: 4122 (init) -> 6157 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:dustmetals: 4098 (init) -> 6172 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorglass: 4126 (init) -> 6148 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactorcontroller: 4121 (init) -> 6149 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinepowertaprf: 4123 (init) -> 6163 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinecomputerport: 4111 (init) -> 6165 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:turbinerotorshaft: 4112 (init) -> 6168 (map).
[09:31:00] [Server thread/DEBUG] [FML/]: Fixed minecraft:items id mismatch bigreactors:reactoraccessport: 4110 (init) -> 6152 (map).
```

I did not check every block or item from Extreme Reactors, sorry. I only noticed the Graphite Block as I was using it as a test for a Nuclear Craft Fission Reactor to check cross-mod functionality. :)

**Comment by ZeroNoRyouki** [comment] 2017-09-24 08:57
The Ludicrite Block recipes are correct. If enderium is available, the second recipe is added

It looks like there is a missing recipe for the Ludicrite block <> ingot conversion

**Comment by ZeroNoRyouki** [comment] 2017-10-01 13:57
Missing recipe fixed in the next release

**Closed by ZeroNoRyouki** 2017-10-01 13:57 UTC
Labels: more information needed

**Comment by sandalle** [comment] 2017-10-02 20:33
Extreme Reactors 1.11.2-0.4.5.42 fixes these issues for me, thank you. :)

**Comment by ZeroNoRyouki** [comment] 2017-10-03 07:26
You are welcome :)
