### ISSUE TITLE
Server - reactor drains all fuel on reboot if on.

### ISSUE THREAD

**Issue by ProsperCraft** [ZeroNoRyouki/BigReactors#41] opened 2016-10-26 22:42 UTC
A player just passed this to me- 

ExtremeReactors-1.10.2-0.4.5.18
Pack- Allthemods 1.39

On each server re-boot "Extreame Reactors" is using up all the Yellorite in it's cores - no power is generated - theYellorite is just gone,  I do have my reactor connected directly to my Mek Induction Matrix, so no cables / lines in-between.   This is on All The Mods server. This has been happening on the last 2 versions. This does not happen while the reactor is off during the re-boot

**Comment by RogueLogic** [comment] 2016-10-27 00:25
Are you sure the fuel is gone because I had a reactor looked empty but have the fuel. They are slightly, *massivly,* different problems.

**Comment by Benorack** [comment] 2016-10-27 02:56
My reactor is 15 x 15 x 3 outside - so 13 x 13 x1 inside. I use 64 fuel rods and 48 graphite blocks inside.
http://prnt.sc/czg2si 
http://prnt.sc/czg36u
http://prnt.sc/czg3dd
Here are some screenshots - the chests and Ender I/O conduits were just recently added.
http://prnt.sc/czg41h - This is where I am connecting directly to the Mekanism Induction Matrix.
Please let me know if you need more information.
Thank you very much for your time in this matter

**Comment by RogueLogic** [comment] 2016-10-27 03:23
a) your reactor seems to be off. *Could be problem with power production?*
b) could you give chunk details. this seems to be similar to erogenousbeef/BigReactors#332.

**Comment by Benorack** [comment] 2016-10-27 03:33
There is no Cyanite dump - of the appox. 900 total Yellorite used so far I've only gotten appox 300 Cyanite.
I will get Chunk details in a few mins

**Comment by RogueLogic** [comment] 2016-10-27 03:41
ok the chunk information is  very important then.

**Comment by Benorack** [comment] 2016-10-27 04:19
having problems getting connected to the server I  will get you the info as soon as I can.

Sorry for the delays.

**Comment by ZeroNoRyouki** [comment] 2016-10-27 09:48
@Benorack : just to be clear, when you open the controller GUI do you see no fuel in the reactor? 

Let's ignore the fuel rods, there is a problem there that I've already fixed.

**Comment by Benorack** [comment] 2016-10-27 10:36
Correct, the first yesterday (Which is when I reported the problem) the GUI was showing a 20% yellow bar indicator.
   My chest which had 3 stacks of yellorite at the time (auto Feeding into the input port) was empty.
   Later on, after several crashes and re-boots the GUI had no yellow indicator bar but was completely black showing a state of 0%.
   No Cyanite at all.

  Hope this helps.

 P.S.  I am unable to get on the server at this time due to a bug with the Elec Core mod which is crashing the server every time I try to log in.
    I've been ask to not log in until they can get a fix for the problem.
     So I will get the chunk location as soon as I  can. 

    On a side note - when I built the reactor I never checked the chunk(s) it was in - so It is very likely that it occupies more the one chunk.

    Again if you need anything please let me know.

    Thank you for your time.

**Comment by ZeroNoRyouki** [comment] 2016-10-27 11:37
I did a quick test in single player with no luck, all worked fine. Could you reproduce it in single player with your current pack?

**Comment by Benorack** [comment] 2016-10-27 12:06
In creative mode or survival mode?

**Comment by Benorack** [comment] 2016-10-27 12:10
Will that help - if it's  a "Sponge" issues I wouldn't have sponge in single player mode - correct?
   But I'll try :)

**Comment by ZeroNoRyouki** [comment] 2016-10-27 12:42
You can do it in creative mode

**Comment by Benorack** [comment] 2016-10-27 14:34
Okay first off I needed to re-install a fresh version of the client. (older system here about 9yrs old so it struggles with this mod pack).
  First test - reactor built in 4 chunks. - logged out then back in all Fuel still there no problems.
  Second test - same reactor but added the Mekanism Induction Matrix. Logged out then back in all Fuel still there no problem.
   Third test - same reactor and Matrix but added the "Spot loader" - same steps as above - All fuel still there no problems.
  Fourth test - Different reactor built in one chuck with the Matrix built in a different chuck with a spot loader - all fuel still there no problems.
  Fifth test  - added Ender I/O item conduits connected to the input and output ports of both of the reactors - Fuel still there no problems.

  So it appears the reactors are not the problem and it may indeed be  something else.

   Again thank you for all your help and time in this matter.

**Comment by RogueLogic** [comment] 2016-10-27 15:23
Please try heading outside of loaded chunks and back again without teleportation. this should cause uneven reactor load as was the case in  erogenousbeef/BigReactors#332, this exact problem.

**Comment by Benorack** [comment] 2016-10-27 21:05
Okay I flew out 1500 blocks away and waited for 1 full min, then flew back to the reactors.
   All fuel was still there and yellorite was still in the chests.

   So again no problems.

    Hope this helps, and again if you need anymore testing please let me know.

   Thank you.

**Comment by Benorack** [comment] 2016-10-27 21:22
I was able to log into the server today and indeed the reactor is in 4 different chunks.

**Comment by ZeroNoRyouki** [comment] 2016-10-27 22:13
@Benorack thank you, I'm closing this then

@RogueLogic : that issue was fixed almost 2 years ago

**Comment by RogueLogic** [comment] 2016-10-27 22:45
And I quote E. Beef "Closing this, as it's solved with a workaround."

**Comment by ZeroNoRyouki** [comment] 2016-10-27 23:09
And you should keep reading...

**Comment by RogueLogic** [comment] 2016-10-27 23:34
When I get home I'll recreate this.

**Comment by RogueLogic** [comment] 2016-10-28 03:24
I GOT IT!

Exactly as i predicted. when outside of spawn chunks i built a reactor with 4 fuel rods each in a different chunk. with my render distance set to 2 heading NW i unloaded one of the four chunks the reactor was in, logged out/in, and BOOM 25% of core gone. Zero you can perform this test yourself.

done twice in a row with no cyanide to show for it.

before:
![2016-10-27_20 22 51](https://cloud.githubusercontent.com/assets/9971693/19793802/4b809e9c-9c83-11e6-89c3-ec2e44836616.png)

after:
![2016-10-27_20 23 26](https://cloud.githubusercontent.com/assets/9971693/19793801/4b7bd7c2-9c83-11e6-8a8e-eeafed5a919e.png)

**Comment by RogueLogic** [comment] 2016-10-28 03:53
this issue has to do with the reactor rebuild on world reload. Zero you *should* be able to figure it out from here.

**Comment by ZeroNoRyouki** [comment] 2016-10-28 19:29
It's deeper than that I'am afraid.

**Comment by RogueLogic** [comment] 2016-10-28 21:54
It may be possible to save if the reactor was paused and lock the values until assembled again. then it shouldn't change the fuel level until the reactor is reassembled, unlocking the values, and keeping the core full.

**Comment by ZeroNoRyouki** [comment] 2016-10-28 23:17
No, it doesn't work like that. What the reactor is doing is actually correct in those circumstances

**Comment by RogueLogic** [comment] 2016-10-28 23:52
I know it is. Besides you, ABookFreak, and E. Beef,  I *probably* know the most about the internals of BR.

**Comment by RogueLogic** [comment] 2016-10-28 23:54
I know it is. Besides you, ABookFreak, and E. Beef,  I *probably* know the most about the internals of BR.

**Comment by ZeroNoRyouki** [comment] 2016-10-29 06:50
Actually, _we_ do.

Fixed in the next release of ZeroCore

**Closed by ZeroNoRyouki** 2016-10-29 06:50 UTC

**Comment by RogueLogic** [comment] 2016-10-29 14:11
Reread my message please. I specifically said besides you, ABookFreak, and E.Beef. I'm probably ~4th.
